<?php

// Load production credentials from env.php (generated by GitHub Actions)
if (file_exists(__DIR__ . '/env.php')) {
    require_once __DIR__ . '/env.php';
    $servername = DB_HOST;
    $username   = DB_USER;
    $password   = DB_PASS;
    $database   = DB_NAME;
} else {
    $servername = "localhost";
    $username   = "root";
    $password   = "";
    $database   = "chat_app";
}

$conn = new mysqli($servername, $username, $password, $database);

if ($conn->connect_error) {
    header('Content-Type: application/json');
    http_response_code(500);
    echo json_encode(['status' => 'error', 'message' => 'Database connection failed']);
    exit;
}

$conn->set_charset('utf8mb4');
